### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by ProfG1** [ProfG1/NeonBreakout#1]

**Comment by ProfG1** [comment]
- [ ]  Make a valid tileset
- [ ]  Make valid characters
- [x]  Make a movement script for the characters
- [ ]  Add health system
- [ ]  Add inventory
- [ ]  Start on the the fighting gameplay
- [ ]  Add hitscan guns
- [ ] add projectiled guns
- [ ]  Make fighting good
- [ ]  Add enemies
- [ ]  Make enemies smart
- [ ]  Add items
- [ ]  Add weapons
- [ ]  Add positive and negative traits
- [ ]  Add small survival aspect of the game
- [ ]  Make prebuilds for the procedural generated map
- [ ]  Make procedural generation
- [ ]  Main menu
- [ ]  Multiplayer Support
- [ ]  Ending
- [ ]  Balancing
- [ ]  Bug-test
- [ ]  Finish Game
